name: Use Reusable Workflow

on:
  push:
    branches-ignore:
      - 'main'
      
  workflow_run:
    workflows: ["go-build.yml"]
    types:
      - completed 

jobs:
  call-reusable-workflow:
    uses: anmawxz/single-workflow/.github/workflows/go-build.yml@main 
    with:
      go-version: '1.20'  
