name: Use Reusable Workflow

on:
  push:
    branches:
      - main
      - dev
      - feature
  pull_request:
    branches:
      - main
      - dev
      - feature

jobs:
  call-reusable-workflow:
    uses: anmaxwz/single-workflow/.github/workflows/go-build.yml@main  
    with:
      go-version: '1.20'  
