name: Go Build

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  call-reusable-workflow:
    uses: anmawxz/single-workflow/.github/workflows/go-build.yml@main 
    with:
      go-version: '1.20' 