name: Use Reusable Workflow Dev

on:
  push:
    branches:
      - main
      - develop
      - feature
  pull_request:
    branches:
      - main
      - develop
      - feature
  workflow_run:
    workflows: ["Reusable Go Build Workflow"]
    types:
      - completed 

jobs:
  call-reusable-workflow:
    uses: anmawxz/single-workflow/.github/workflows/go-build.yml@main 
    with:
      go-version: '1.20'
